import { Inter } from "next/font/google";
import "./globals.scss";
import Script from 'next/script';

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script type="module" src="/swup.js" strategy="afterInteractive"/>

      <body className={`${geistSans.variable} pages`}>
        {children}
      </body>
    </html>
  );
}
